/**
 * Домены, которые ходят мимо тоннеля.
 *
 * Список собран из исследования `IREK-direct-routing-research.md` в корне
 * репозитория: только проверенный реестр, раздел «следующие кандидаты» не
 * включён. Правила даны с префиксом `domain:` — это домен и все его
 * поддомены. Голые строки в Xray означают поиск подстроки и цепляют лишнее,
 * поэтому здесь их нет. Совместимость проверена: ядро принимает весь список.
 *
 * Чего в списке намеренно нет: geoip и geosite (у клиентов нет геофайлов, и
 * одно такое правило роняет весь профиль), всех зон .ru целиком, облачных
 * диапазонов и общих CDN.
 *
 * Яндекс Браузер не исключается целиком: маршрут выбирается по адресу сайта,
 * а не по приложению, поэтому зарубежные сайты внутри него идут через VPN.
 *
 * 🔴 Прямой трафик идёт с настоящего адреса человека. Это осознанный размен:
 * банки и госуслуги не любят зарубежные адреса.
 */
export const DIRECT_SITES: string[] = [
  // Банки
  "domain:abr.ru",
  "domain:absolutbank.ru",
  "domain:akbars.ru",
  "domain:alefbank.com",
  "domain:alfa.me",
  "domain:alfabank.ru",
  "domain:alfabank.st",
  "domain:alfadirect.ru",
  "domain:ankb.ru",
  "domain:atb.su",
  "domain:avangard.ru",
  "domain:aversbank.ru",
  "domain:bank.yandex.ru",
  "domain:bank131.com",
  "domain:bankermak.ru",
  "domain:bbr.ru",
  "domain:bcs-bank.ru",
  "domain:bcs.ru",
  "domain:bfa.ru",
  "domain:blanc.ru",
  "domain:broker.ru",
  "domain:bspb.ru",
  "domain:cdn-tinkoff.ru",
  "domain:credit-zenit.ru",
  "domain:dbo-dengi.online",
  "domain:domrfbank.ru",
  "domain:finambank.ru",
  "domain:forshtadt.ru",
  "domain:gazprombank.com",
  "domain:gazprombank.investments",
  "domain:gazprombank.ru",
  "domain:gid.ru",
  "domain:gpb.ru",
  "domain:hva.im",
  "domain:id.ru",
  "domain:kubankredit.ru",
  "domain:mfk-bank.ru",
  "domain:mkb.ru",
  "domain:mtsbank.ru",
  "domain:mtsdengi.ru",
  "domain:my-tbank.ru",
  "domain:myapelsin.ru",
  "domain:noosferabank.ru",
  "domain:otpbank.ru",
  "domain:ozon-credit.ru",
  "domain:ozon.ru",
  "domain:ozoncard.ru",
  "domain:payment.ru",
  "domain:paywb.com",
  "domain:paywb.ru",
  "domain:pochtabank.ru",
  "domain:primbank.ru",
  "domain:psb-ocenka.ru",
  "domain:psb.ru",
  "domain:psbank.ru",
  "domain:pskb.ru",
  "domain:raiffeisen-media.ru",
  "domain:raiffeisen.ru",
  "domain:rencredit.ru",
  "domain:rosbank.ru",
  "domain:rshb.ru",
  "domain:sber.ru",
  "domain:sberbank.com",
  "domain:sberbank.ru",
  "domain:sbrf.ru",
  "domain:sinara.ru",
  "domain:solid.ru",
  "domain:sovcombank.ru",
  "domain:t-bank-app.ru",
  "domain:t-bank-app.su",
  "domain:t-static.ru",
  "domain:tatsotsbank.ru",
  "domain:tbank-online.com",
  "domain:tbank.ru",
  "domain:tcsbank.ru",
  "domain:tinkoff.ru",
  "domain:tkbbank.ru",
  "domain:tochka-tech.com",
  "domain:tochka.com",
  "domain:uralsib.ru",
  "domain:vtb-direct.com",
  "domain:vtb.ru",
  "domain:wb-bank.ru",
  "domain:wbpay.ru",
  "domain:xn--d1aqf.xn--p1ai",
  "domain:yandex-bank.net",
  "domain:zenit-card.ru",
  "domain:zenit.ru",
  "domain:ziraatbank.ru",

  // Оплата
  "domain:best2pay.net",
  "domain:nspk.ru",
  "domain:payecom.ru",
  "domain:platiecom.ru",

  // Маркетплейсы и магазины
  "domain:acmvid.com",
  "domain:avito.ru",
  "domain:avito.st",
  "domain:citilink.ru",
  "domain:detmir.ru",
  "domain:dns-com.ru",
  "domain:dns-shop.ru",
  "domain:fix-price.com",
  "full:mvideo.edna.io",
  "domain:lamoda.ru",
  "domain:megamarket.ru",
  "domain:megamarket.tech",
  "domain:mvideo.ru",
  "domain:o3.ru",
  "domain:o3t.ru",
  "domain:ozon.app",
  "domain:ozon.com",
  "domain:ozon.ru",
  "domain:ozone.ru",
  "domain:ozonusercontent.com",
  "domain:sbermegamarket.ru",
  "domain:wb-basket.ru",
  "domain:wb.ru",
  "domain:wbbasket.ru",
  "domain:wbcontent.net",
  "domain:wbstatic.net",
  "domain:wbstatic.ru",
  "domain:wildberries.ru",

  // Продукты и доставка
  "domain:5ka.ru",
  "domain:auchan.ru",
  "domain:av.ru",
  "domain:chizhik.club",
  "domain:clubx5.ru",
  "domain:dixy.ru",
  "domain:dodois.com",
  "domain:dodois.io",
  "domain:dodopizza.com",
  "domain:dodopizza.ru",
  "domain:dodostatic.net",
  "domain:dostaevsky.ru",
  "domain:idx5.ru",
  "domain:kazanexpress.ru",
  "domain:kuper.ru",
  "domain:lenta.com",
  "domain:lenta.tech",
  "domain:magnit.com",
  "domain:magnit.ru",
  "domain:metro-cc.ru",
  "domain:mm.ru",
  "domain:myspar.ru",
  "domain:perekrestok.com",
  "domain:perekrestok.ru",
  "domain:restnproducts.ru",
  "domain:rostics.ru",
  "domain:samokat.ru",
  "domain:uni.rest",
  "domain:unirest.tech",
  "domain:vkusnoitochka.ru",
  "domain:vkusvill.ru",
  "domain:x5.ru",
  "domain:x5club.ru",
  "domain:x5id.ru",
  "domain:x5paket.ru",
  "domain:x5static.net",

  // Аптеки
  "domain:366.ru",
  "domain:apteka-april.ru",
  "domain:apteka.ru",
  "domain:aptekiplus.ru",
  "domain:eaptechka.online",
  "domain:eapteka.ru",
  "domain:farmlend.ru",
  "domain:gorzdrav.org",
  "domain:megapteka.ru",
  "domain:planetazdorovo.ru",
  "domain:pz.help",
  "domain:rigla.ru",
  "domain:stolichki.ru",
  "domain:uteka.ru",
  "domain:zdravcity.ru",

  // Яндекс
  "domain:clck.ru",
  "domain:kinopoisk-ru.clstorage.net",
  "domain:kinopoisk.ru",
  "domain:ya.cc",
  "domain:ya.ru",
  "domain:yandex.com",
  "domain:yandex.net",
  "domain:yandex.ru",
  "domain:yandexgo.com",
  "domain:yastat.net",
  "domain:yastatic-net.ru",
  "domain:yastatic.net",
  "domain:yccdn.ru",
  "domain:yndx.net",

  // Госуслуги и медицина
  "domain:ebs.ru",
  "domain:emias.info",
  "domain:emias.ru",
  "domain:goskey.ru",
  "domain:gosuslugi.ru",
  "domain:gu-st.ru",
  "domain:mos.ru",
  "domain:mosreg.ru",
  "domain:nalog.ru",

  // Автомобиль и транспорт — кандидаты
  "domain:2gis.ae",
  "domain:2gis.am",
  "domain:2gis.az",
  "domain:2gis.by",
  "domain:2gis.com",
  "domain:2gis.com.cy",
  "domain:2gis.cz",
  "domain:2gis.ge",
  "domain:2gis.kg",
  "domain:2gis.kz",
  "domain:2gis.ru",
  "domain:2gis.tech",
  "domain:2gis.tj",
  "domain:2gis.uz",
  "domain:avtodor-tr.ru",
  "domain:belkacar.ru",
  "domain:citydrive.ru",
  "domain:delimobil.ru",
  "domain:pandora-on.com",
  "domain:parking.mos.ru",
  "domain:starline.online",
  "domain:starline.ru",
];

/** Версия профиля. Поднимать РУКАМИ при изменении списка: по ней клиент решает, обновляться ли. */
export const ROUTING_VERSION = "1789246800";
